--DROP TABLE IF EXISTS npc;
CREATE TABLE npc(
  id decimal(11,0) NOT NULL default 0,
  idTemplate integer NOT NULL default 0,
  name varchar(200) default NULL,
  serverSideName integer default 0,
  title varchar(45) default '',
  serverSideTitle integer default 0,
  class varchar(200) default NULL,
  collision_radius decimal(5,2) default NULL,
  collision_height decimal(5,2) default NULL,
  "level" decimal(2,0) default NULL,
  sex varchar(6) default NULL,
  type varchar(21) default NULL,
  attackrange integer default NULL,
  hp decimal(8,0) default NULL,
  mp decimal(8,0) default NULL,
  hpreg decimal(8,2) default NULL,
  mpreg decimal(5,2) default NULL,
  str decimal(7,0) default NULL,
  con decimal(7,0) default NULL,
  dex decimal(7,0) default NULL,
  "int" decimal(7,0) default NULL,
  wit decimal(7,0) default NULL,
  men decimal(7,0) default NULL,
  exp decimal(9,0) default NULL,
  sp decimal(8,0) default NULL,
  patk decimal(5,0) default NULL,
  pdef decimal(5,0) default NULL,
  matk decimal(5,0) default NULL,
  mdef decimal(5,0) default NULL,
  atkspd decimal(3,0) default NULL,
  aggro decimal(6,0) default NULL,
  matkspd decimal(4,0) default NULL,
  rhand decimal(5,0) default NULL,
  lhand decimal(5,0) default NULL,
  armor decimal(1,0) default NULL,
  walkspd decimal(3,0) default NULL,
  runspd decimal(3,0) default NULL,
  faction_id varchar(40) default NULL,
  faction_range decimal(4,0) default NULL,
  isUndead integer default 0,
  absorb_level decimal(2,0) default 0,
  absorb_type varchar(16) DEFAULT 'LAST_HIT' NOT NULL,
  ss integer default 0,
  bss integer default 0,
  ss_rate integer default 0,
  AI varchar(8) default 'fighter',
  drop_herbs varchar(5) DEFAULT 'false' NOT NULL,
  PRIMARY KEY (id)
);
